apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-cpu
  namespace: openshift-gitops
spec:
  destination:
    namespace: apps-demo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app
    repoURL: https://github.com/n-able-demo/demo-app-infra.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
